name: 'git-flow-merge-action'
description: 'merge branch to master and develop branch, and add tag'
author: 'Yasuharu Yanamura'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  branch:
    description: 'release or hotfix branch'
    required: true
  develop_branch:
    description: 'develop branch name'
    default: 'develop'
  main_branch:
    description: 'main branch name'
    default: 'master'
  tag:
    description: 'tag name'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: "git-merge"
  color: "black"
